# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'predictWindow.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_formResult(object):
    def setupUi(self, formResult):
        formResult.setObjectName("formResult")
        formResult.setWindowModality(QtCore.Qt.NonModal)
        formResult.setEnabled(True)
        formResult.resize(1000, 618)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(formResult.sizePolicy().hasHeightForWidth())
        formResult.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(13)
        formResult.setFont(font)
        formResult.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(formResult)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_text = QtWidgets.QLabel(formResult)
        font = QtGui.QFont()
        font.setPointSize(34)
        font.setBold(True)
        font.setWeight(75)
        self.label_text.setFont(font)
        self.label_text.setTextFormat(QtCore.Qt.PlainText)
        self.label_text.setWordWrap(True)
        self.label_text.setObjectName("label_text")
        self.verticalLayout.addWidget(self.label_text)
        self.progress_predict = QtWidgets.QProgressBar(formResult)
        self.progress_predict.setProperty("value", 0)
        self.progress_predict.setObjectName("progress_predict")
        self.verticalLayout.addWidget(self.progress_predict)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.button_law1 = QtWidgets.QPushButton(formResult)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.button_law1.sizePolicy().hasHeightForWidth())
        self.button_law1.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(24)
        font.setUnderline(True)
        self.button_law1.setFont(font)
        self.button_law1.setFlat(True)
        self.button_law1.setObjectName("button_law1")
        self.horizontalLayout.addWidget(self.button_law1)
        self.button_law2 = QtWidgets.QPushButton(formResult)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.button_law2.sizePolicy().hasHeightForWidth())
        self.button_law2.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(24)
        font.setUnderline(True)
        self.button_law2.setFont(font)
        self.button_law2.setFlat(True)
        self.button_law2.setObjectName("button_law2")
        self.horizontalLayout.addWidget(self.button_law2)
        self.button_law3 = QtWidgets.QPushButton(formResult)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.button_law3.sizePolicy().hasHeightForWidth())
        self.button_law3.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(24)
        font.setUnderline(True)
        self.button_law3.setFont(font)
        self.button_law3.setAutoDefault(False)
        self.button_law3.setFlat(True)
        self.button_law3.setObjectName("button_law3")
        self.horizontalLayout.addWidget(self.button_law3)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.verticalLayout.setStretch(0, 1)
        self.verticalLayout.setStretch(1, 1)
        self.verticalLayout.setStretch(2, 2)
        self.horizontalLayout_2.addLayout(self.verticalLayout)

        self.retranslateUi(formResult)
        QtCore.QMetaObject.connectSlotsByName(formResult)

    def retranslateUi(self, formResult):
        _translate = QtCore.QCoreApplication.translate
        formResult.setWindowTitle(_translate("formResult", "神经网络预测结果"))
        self.label_text.setText(_translate("formResult", "经预测，与该案情相符的法条为："))
        self.button_law1.setText(_translate("formResult", "waiting"))
        self.button_law2.setText(_translate("formResult", "waiting"))
        self.button_law3.setText(_translate("formResult", "waiting"))

